### ISSUE TITLE
Honey has a strange behavior with blocks that have the same density  

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#119] opened 2024-03-18 18:48 UTC
A teacher during the Buoyancy feedback identified the next:

dropped object of same density as honey into honey and the top of the totally submerged object remained flush with fluid surface (no matter the drop height).
dropped object (of same density) into a custom fluid having the same density as honey and the totally submerged object could be observed suspended some distance below the surface of the fluid (final distance below surface affected by drop height) 

object with the same density of honey dropped in honey at any height:
![image](https://github.com/phetsims/buoyancy/assets/26031501/0a6d60a5-915d-4f63-b1d8-53c513d0b0d1)

same object in a fluid with the same density of honey, just by changing honey to custom:
![Buoyancy](https://github.com/phetsims/buoyancy/assets/26031501/f096c29d-337c-4cba-8c18-089b1154d362)

same object dropped from a height in a custom fluid with the same density as honey:

![image](https://github.com/phetsims/buoyancy/assets/26031501/4f520312-eea0-4223-87a8-c533ad95be6e)

**Comment by zepumph** [comment] 2024-03-18 18:53
I wonder if this is just a drawing error? Could changing the material cause this to go away? @AgustinVallejo also mentioned that this may just be working as expected. I feel like the main bug is in seeing "100% submerged" when there is still a layer of block showing without liquid on top. We will get to this bug after we are feature complete though.

**Comment by samreid** [comment] 2024-05-28 22:14
Let's look at this together in a standup

**Comment by samreid** [comment] 2024-05-29 16:11
@AgustinVallejo @DianaTavares and I reproduced the problem today, and saw that sometimes an object with density of 1.44 shows the top, and sometimes it does not. This is because the true model value is not exactly 1.44, but some number that rounds to 1.44.  For instance, when I pressed the slider button to the right, the number remained showing 1.44, but it caused the top to go underhoney. We discussed that we could change the model to have the exact values that are shown, but that would be worse because it would cause non-uniform step sizes in the slider deltas. We agreed to close the issue.

**Closed as completed by samreid** 2024-05-29 16:11 UTC
Labels: type:bug, meeting:design
