### ISSUE TITLE
Fluctuating values of on the scales

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#157] opened 2024-05-15 00:58 UTC
Some scales have fluctuating values. The gif shows some examples in Intro:

![Untitled](https://github.com/phetsims/buoyancy/assets/26031501/7045eeb1-b25c-4e74-9625-37a095349532)

**Comment by zepumph** [comment] 2024-05-15 15:49
I believe this is a duplicate of https://github.com/phetsims/buoyancy/issues/64

**Closed as completed** 2024-05-15 16:24 UTC
