### ISSUE TITLE
“Force values” inactive when there are no forces selected

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#159] opened 2024-05-15 01:11 UTC
During the interviews, users  (especially students), click on "force values" when they didn't have any force active, which means that nothing happened in the simulation. Then, they unselect the Force values and did not click on them again until I asked them to do it for a deep analysis of the forces. 

I think that this control can be inactive when there are not forces selected, and with at least one force, this control can be active, ready for users to select and unselect it. 
![image](https://github.com/phetsims/buoyancy/assets/26031501/7dd66980-0f3f-4489-a98c-6c865dd1a701)

**Comment by zepumph** [comment] 2024-05-15 15:50
I guess is that this is a regression from the decoration layer work. Assigning to @samreid to see if he can make progress, but feel free to toss things back to me.

**Comment by samreid** [comment] 2024-05-17 14:23
> I guess is that this is a regression from the decoration layer work.

The decoration work was done in https://github.com/phetsims/density-buoyancy-common/issues/111 on April 16. Testing https://phet-dev.colorado.edu/html/buoyancy/1.0.0-dev.3/phet/buoyancy_en_phet.html which was published April 7 has the same behavior. So it would be good to clarify what @zepumph is referring to.

Let's also check on the design for this, since the "Force Values" is separated from the Gravity/Buoyancy/Contact checkboxes. And it could be confusing for a student to know why it is grayed out. Or if a student clicks "Gravity" then "Force Values" then unchecks "Gravity". Then "Force values" would be checked and grayed out and the student could not uncheck it without checking another box first. Should we gray out the "Vector scale" +/- buttons when the vectors are hidden? I think that would have the same problems. Maybe just moving the "Force Values" checkbox under the Vector Scale buttons would help the user know it applies to those forces.

**Comment by samreid** [comment] 2024-05-17 16:26
In discussion today, we agreed to move the "Force Values" underneath the Vector Scale control, and it will not gray out. 

* Try an on off switch for the force values
* Rename masses => Mass Values
* Put "Force Values" above the separator, below the vector scale button
* Do not enable/disable

**Comment by samreid** [comment] 2024-05-17 20:37
@marlitas @zepumph and I tried the on off switch and it doesn't seem good:

<img width="457" alt="image" src="https://github.com/phetsims/buoyancy/assets/679486/f4a69293-8b0f-469c-b6a4-40ce9e5b182f">

**Comment by zepumph** [comment] 2024-05-17 22:28
Looks perfect thanks. Won't we need a migration rule for density in regards to the showMassesProperty rename?

**Comment by samreid** [comment] 2024-05-17 22:33
I did that in https://github.com/phetsims/phet-io-sim-specific/commit/198645cfc9c2d43283329e7634669d2ddfc7e63f

**Comment by zepumph** [comment] 2024-05-17 22:40
ARRG! Of course it is at the end of the commit. Sorry. Thanks.

**Closed as completed by zepumph** 2024-05-17 22:40 UTC
Labels: type:bug, status:ready-for-review
