### ISSUE TITLE
Better PhET-iO support for Shapes

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#160] opened 2024-05-17 18:33 UTC
https://github.com/phetsims/buoyancy/issues/153 is breaking CT and showing that we are not currently supporting dynamic shape instances well. I'll create a new issue to discuss.

@samreid and I dug up https://github.com/phetsims/phet-io/issues/1454 as we remembered out history with heterogeneous dynamic element containers, most importantly about how we decided not to support them. Here are some quotes:

>UPDATE from 11/15/19: We decided against this because PhetioGroups are not necessarily the data structure used in the sim for storing dynamic elements, so instead of making PhetioGroups more complicated by supporting heterogenous groups, we decided it made more sense to create a Group for every type. If you need support for a heterogeneous group, you can create an ObservableArray that holds elements from multiple PhetioGroups by reference.

We outlined two problems that may need attention:
1. The biggest worry about our current heterogeneous setup is how subtype specific subProperties are not in the API. for example Cuboid.sizeProperty, Cone.heightProperty, Cone.radiusProperty and others.
2. Let's say that to solve the above, we move all subtype properties into Mass, so we can still have PhetioCapsuleIO<MassIO>, then we need to adjust logic such that the archetype describes a MassIO, and not a subtype, AND we need to make sure that the API validation logic supports creating a subtype phetioTypeName.

Noting here that the assertion over in https://github.com/phetsims/buoyancy/issues/153 isn't just for the type itself. It will also fail out because the `radiusProperty` etc isn't in the archetype. So more discussion here is needed.

**Comment by zepumph** [comment] 2024-05-17 18:34
Noting how this should be have originally been done in https://github.com/phetsims/buoyancy/issues/61

**Comment by zepumph** [comment] 2024-05-22 20:22
@AgustinVallejo @samreid and I would like to proceed by having a single PhetioCapsule per MassShape per object. So ObjectA gets a whole set of PhetioCapsules, and so does ObjectB. Here is the potential studio tree look:

```


objects
	objectA
		elementProperty
		capsules
			blockCapsule
			coneCapsule
			etc	
	objectB
		elementProperty
		capsules
			blockCapsule
			coneCapsule
			etc
```

**Comment by samreid** [comment] 2024-05-30 01:16
I considered that center and variability became much simpler when we eliminated the phet-io group, and we designed projectile data lab to have no PhetioGroup or PhetioCapsule. I tested creating each shape statically during startup in this context and saw that in a built sim, the memory footprint was still only 75MB which is acceptable. So this simulation will be better off without any PhetioCapsules at all. After the change, I confirmed that Studio=>Launch works well and preserves the shape selection and customization. Closing.

**Comment by phet-dev** [comment] 2024-05-30 09:29
Reopening because there is a TODO marked for this issue.

**Comment by samreid** [comment] 2024-05-30 13:39
Moved unrelated TODOs to side issues, closing.

**Comment by samreid** [comment] 2024-05-30 15:27
@AgustinVallejo recommended running this past @zepumph so he is aware that the static preallocation was a good solution here. Reopening for review, please close if all is well.

**Comment by zepumph** [comment] 2024-06-03 18:23
This is very clean. Nice job. I see how PhET-iO state is run off of the enumeration Property, and that is excellent. I believe we may want to instrument the mass Property as a ReferenceIO pointing to the active mass. That would make writing a wrapper a fair bit easier to get the active masses for data capture/manipulation, but let's see what @arouinfar thinks.  I'll write it as a design question over in https://github.com/phetsims/buoyancy/issues/51.

Everything else looks very good to me. Thanks

**Comment by zepumph** [comment] 2024-06-03 19:07
Actually. I don't like the notion of "a" and "b". It should be "primary" and "secondary".

`groupA` -> `primaryMasses`
`aMap` -> `primaryMassesMap`

or whatever you think it best.

**Comment by samreid** [comment] 2024-06-03 20:12
Let's also get @arouinfar opinion on that tandem.  Assigning to her for next iteration.

**Comment by samreid** [comment] 2024-06-07 13:21
I moved the tandem naming part to a new issue, closing.

**Closed as completed by samreid** 2024-06-07 13:21 UTC
Labels: dev:phet-io, status:ready-for-review
