### ISSUE TITLE
Cube on the ground is considered part of the pool

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#139] opened 2024-04-16 21:47 UTC
@samreid and I discovered this while working on https://github.com/phetsims/buoyancy/issues/135. It may be as easy as caring about horizontal position in `Pool.isMassInside()`.

**Comment by samreid** [comment] 2024-05-30 02:06
BoatBasin has a slip factor for when the shapes penetrate due to the physics engine:

https://github.com/phetsims/density-buoyancy-common/blob/a5fc58b0f83696d6afc61da1746e6c1c5f5c1244/js/buoyancy/model/BoatBasin.ts#L31-L39

Masses sitting on the ground are actually at around y=-0.001.  But since even with high volume objects the pool does not get near the top, it seems safe to add a slip factor here as well.

**Comment by samreid** [comment] 2024-05-30 02:07
I added the same slip factor that is used in BoatBasin and confirmed it is working correctly. I tested some behavior of putting blocks in and out of the fluid. I documented why the horizontal measures are unnecessary. Closing.

**Closed as completed by samreid** 2024-05-30 02:07 UTC
Labels: dev:code-review
