### ISSUE TITLE
Cannot click on edge of a cylinder

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#103] opened 2024-02-19 22:07 UTC
To reproduce:
1. Shapes screen
2. choose either type of cylinder
3. Try to drag around a cylinder by clicking on the tapered edge it. If you click on the center (closed part to you), it works, but otherwise I can't start a drag from the edge.

@AgustinVallejo can you reproduce this?

**Comment by AgustinVallejo** [comment] 2024-02-20 20:10
I can also reproduce on my end, will take a look.

**Comment by samreid** [comment] 2024-04-15 22:44
I'd like to work on this one, self assigning and unassigning @AgustinVallejo.

**Comment by samreid** [comment] 2024-04-15 23:45
Fixed in the commits and it's working well in my testing. I tested with vertical and horizontal cylinders of different widths and heights and it seemed well-behaved. In my testing, I observed a 1px perimeter where the mouse is a hand but the object is not draggable. This may indicate that the code deciding whether to show a hand calls different code than *Cylinder.intersect. Should we investigate?

@zepumph or @AgustinVallejo can you please review the changes, test thoroughly and comment on the question above? Also please comment if there are other ways this code should be tested.

**Comment by samreid** [comment] 2024-04-19 18:16
It looks like the cone is buggy too.

**Comment by AgustinVallejo** [comment] 2024-04-19 18:57
Pushing a fix for the cone issue mentioned above, it was way simpler and due to the interactive highlight.

**Comment by AgustinVallejo** [comment] 2024-04-19 20:04
Looking good! Closing, thanks @samreid

**Closed as completed by AgustinVallejo** 2024-04-19 20:04 UTC
Labels: type:bug, status:ready-for-review
